/*
  # Seed listing_zips for existing listings

  Populates listing_zips rows for all listings that already have public media assets.
  This ensures existing listings get their ZIPs generated by the pg_cron job.

  For each listing with media, creates rows for:
    - Each distinct media kind that has assets
    - An 'all' row if the listing has any assets

  All seeded rows are set to 'stale' so the cron job picks them up immediately.
*/

-- Seed per-kind ZIP rows for existing listings
INSERT INTO public.listing_zips (listing_id, kind, status, stale_since)
SELECT DISTINCT ma.listing_id, ma.kind, 'stale', now()
FROM public.media_assets ma
WHERE ma.is_public = true
ON CONFLICT (listing_id, kind) DO NOTHING;

-- Seed 'all' ZIP rows for existing listings that have any media
INSERT INTO public.listing_zips (listing_id, kind, status, stale_since)
SELECT DISTINCT ma.listing_id, 'all', 'stale', now()
FROM public.media_assets ma
WHERE ma.is_public = true
ON CONFLICT (listing_id, kind) DO NOTHING;